<?php
namespace Initially\Rpc\Core\Support;

use Monolog\Handler\StreamHandler;
use Monolog\Logger;
use PHPUnit_Framework_TestCase;

class LoggerProxyTest extends PHPUnit_Framework_TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $stream = new StreamHandler(__DIR__ . "/../../../../initially-rpc.log", Logger::DEBUG);
        $mLogger = new Logger("initially-rpc");
        $mLogger->pushHandler($stream);
        LoggerProxy::setLogger($mLogger);
    }

    public function testRecordLog()
    {
        $logger = LoggerProxy::getInstance();
        $result = $logger->debug("test", array("proxy" => 1234));
        $this->assertTrue($result);
    }

}